### PR TITLE
ODS Docker image

### PR DESCRIPTION
**Pull request by LinusCastelino**
Created Docker image for ODS.

Updated the README with additional installation instructions.

With this setup, we could execute ODS as containers rather than having to run it as a standalone service on a host machine. 
A huge benefit will be the scaling functionality provided by Docker which we can explore in future to support larger volumes of requests.

I have been learning Docker over the past few days and was able to come up with this setup which is optimal according to me. Being new to this technology, I may be wrong.
If anyone has suggestions for improving it, please pitch in.

Note to Reviewers -
Ensure you install Docker and follow the instructions to start ODS. If you are unable to complete the setup or face any issues, please ping me on slack.
Please approve the PR only if you are able to access ODS on your web browser after starting the Docker containers.

### CODE REVIEW

**Review by yinyifu — DISMISSED** [review]

**Comment by ryandils** [comment]
Is there a way that we can automate the process of spinning up of the database using something like a Makefile?

**Comment by LinusCastelino** [comment]
@RyChrome I don't think I completely understand what you are trying to suggest.

Also, I am not sure if a Makefile can be run on Windows machines. Would require additional utility installations.

The docker-compose file includes functionality for starting up MongoDB as well. If you run it, both MongoDB and ODS start up. 
I have set up the dependency in a way that ODS Maven process starts up only after MongoDB is up and running.

If you are suggesting something different than this, please provide more details.

**Comment by LinusCastelino** [comment]
Anyone planning to review this PR? Pending since 8 days.

**Comment by aashish-jain** [comment]
Will do it before tomorrow.

with regards,
Aashish

**Review by ryandils — APPROVED** [review]
Looks good. Nice Job Linus!

**Pull request merged**
