### PR TITLE
Added unit test cases for App.js, Actions.js, Reducers.js

### PR DESCRIPTION
**Pull request by prakhathi-m**

### CODE REVIEW

**Comment by prakhathi-m** [comment]
[Frontend test cases for App.s](https://trello.com/c/lvXobjnd/111-frontend-test-cases-for-apps)

**Comment by prakhathi-m** [comment]
[Frontend test cases for Reducers.js](https://trello.com/c/iiFuhGIQ/112-frontend-test-cases-for-reducersjs)

**Comment by prakhathi-m** [comment]
[Frontend test cases for actions.js](https://trello.com/c/NZsyk7YA/113-frontend-test-cases-for-actionsjs)

**Review by aashish-jain — APPROVED** [review]
Changes look good.

**Pull request closed without merging**
