### PR TITLE
fixed login responsiveness

### PR DESCRIPTION
**Pull request by ethirocks**
https://trello.com/c/w6JWr6bu/63-fix-signin-page-issue-on-mobile

### CODE REVIEW

**Review by LinusCastelino — APPROVED** [review]
Sliding transition removed and css property edited.
Looks good!
Please test once merged into master

**Comment by LinusCastelino** [comment]
@ethirocks  @yifuBA 

Changes pushed in this PR is affecting the homepage since there is a slick slider there too.
The homepage is showing up a horizontal slider with a blank space at the right. The arrows for the carousel have also disappeared.
Please check and remove the exact property causing the issue rather than commenting out the whole CSS configuration.

image

**Comment by LinusCastelino** [comment]
Never mind.. fixed it

**Comment by ethirocks** [comment]
My bad!!

**Pull request merged**
