### PR TITLE
Code updated to React 18. Upgraded Mui to v5, Reacter router dom to v6.

### PR DESCRIPTION
**Pull request by jarvis1897**
The code was updated to React version 18. There have been major updates in MUI dependency. The @material-ui dependency isn't supported by React 18. It was upgraded to version 5.
Due to this, there have been some changes in the UI, particularly the transfer page:
Before:
image
After:
image
I have tried various methods to make it look like before. Including trying to do it via CSS and using mui-specific style elements. However, it doesn't respond to changes in the border around the button components.

Similarly, react-router-dom was upgraded to v6. All the routes are working fine. 

Please review and comment.

### CODE REVIEW

**Comment by idkuri** [comment]
Bug: theme.palette.text is undefined

How to replicate:
1) run npm install -f
2) npm start
3) login and try to access the queue page.

Here's a screenshot:
image

**Comment by jarvis1897** [comment]
@idkuri Did you need to do a force install due to a conflict in dependencies?

**Comment by jarvis1897** [comment]
Queue components merged to react-upgrade branch.
@idkuri

**Comment by idkuri** [comment]
image
More errors please check

**Pull request closed without merging**
