### PR TITLE
show -hide password implementation

### PR DESCRIPTION
**Pull request by hShivaprakash**
Eye symbol on password fields

### CODE REVIEW

**Comment by LinusCastelino** [comment]
Functionality testing done (test artifacts pasted below)

Login
image

User page (Change password)
image

Forgot Password
image

Registration
image

**Comment by LinusCastelino** [comment]
@hShivaprakash 
Please fix the merge conflicts.

**Review by aashish-jain — COMMENTED** [review]
Looks good. Please fix the merge conflicts.

**Review by aashish-jain — APPROVED** [review]

**Comment by aashish-jain** [comment]
Closing this PR. Reopen this PR to merge the changes to the dev branch

**Pull request merged**
