### PR TITLE
Backup Script for Database

### PR DESCRIPTION
**Pull request by KiranPrabhakar135**

### CODE REVIEW

**Review by aashish-jain — APPROVED** [review]

**Review by LinusCastelino — CHANGES_REQUESTED** [review]
Good job with the comments.
Script looks good. However, the echo statements will never be read by anyone. Need to change that.
Also, we need to use mailx and send a notification after each run of the script to confirm if it ran successfully.
Let's discuss additional improvements to this tomorrow.

**Comment by KiranPrabhakar135** [comment]
Good review comments 🥇 👍 . Incorporated all of them.
The scripts will now catch exceptions on Mongo dump, tar, upload and delete from s3. 
Emails's will be triggered on error and on completion of the backup.

**Review by LinusCastelino — COMMENTED** [review]
Neatly done.
Although I'll hold the approval until Tues to watch a demo.

**Comment by KiranPrabhakar135** [comment]
Incorporated Success and Error in the email subject

**Review by LinusCastelino — APPROVED** [review]

**Comment by LinusCastelino** [comment]
Looks good now!

**Pull request merged**
